FROM golang:1.25-alpine AS builder

ENV GOPROXY=https://proxy.golang.org,direct
ENV CGO_ENABLED=0

WORKDIR /app

COPY backend/go.mod backend/go.sum ./

# Скачиваем зависимости
RUN go mod download

# Копируем остальной код
COPY backend/ .

# !!! КЛЮЧЕВОЙ ШАГ: обновляем go.mod перед сборкой !!!
RUN go mod tidy

# Собираем приложение
RUN go build -o main .

# Финальный образ
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/main .
#COPY --from=builder /app/.env .env || true

EXPOSE 8080

CMD ["./main"]
